name: regulatory_suite
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python e utilitários essenciais
  - python=3.11
  - pip>=23.0.0  # Definição de versão mínima para pip
  - setuptools>=68.2.2
  - wheel>=0.41.2

  # Processamento de dados
  - pandas>=2.1.3
  - numpy>=1.26.2
  - python-dateutil>=2.8.2

  # Interface Web
  - streamlit>=1.27.0

  # Machine Learning / NLP - Mantemos suporte para T5 e outras IA relevantes
  - pytorch::pytorch>=2.0.0
  - transformers>=4.36.0
  - spacy>=3.7.2
  - scikit-learn>=1.3.2
  - huggingface_hub>=0.16.4
  - tiktoken>=0.5.2  # Mantido para futuras análises
  - sentencepiece>=0.1.99  # Necessário para modelos T5/ptt5
  - tokenizers>=0.15.0  # Essencial para eficiência na tokenização de textos

  # Web scraping e APIs
  - requests>=2.31.0  # Para chamadas HTTP às APIs do Senado e da Câmara
  - beautifulsoup4>=4.12.2  # Para extração de dados de páginas HTML
  - lxml>=4.9.3  # Melhora a performance ao analisar HTML/XML
  - unidecode>=1.3.7  # Para normalização de textos
  - xmltodict>=0.13.0  # Para processar respostas XML da API do Senado
  
  # Visualização e relatórios
  - plotly>=5.18.0
  - seaborn>=0.12.2

  # Testes e qualidade de código
  - pytest>=7.4.0
  - black>=23.10.0
  - flake8>=6.1.0
  - mypy>=1.5.1

  # Dependências via pip
  - pip:
    - protobuf>=4.24.4
    - torchinfo>=1.8.0
    - textblob>=0.17.1
